export {default as Navbar} from './Navbar/Navbar';
export {default as Home} from './Home/Home';
export {default as Search} from './Search/Search';
export {default as Login} from './Login/Login';
export {default as Profiles} from './Profiles/Profiles';
export {default as Menu} from './Menu/Menu';
export {default as Movies} from './Movies/Movies';
export {default as MovieList} from './MovieList/MovieList';
export {default as Movie} from './Movie/Movie';
